name: andertaxi
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=$RMQ_User
      - RABBITMQ_DEFAULT_PASS=$RMQ_Pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmqqueuegenerator:
    image: rabbitmqqueuegenerator
    build:
      context: .
      dockerfile: RabbitMqQueueGenerator/Dockerfile
    container_name: rabbitmqqueuegenerator
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  closestdriverservice:
    image: closestdriverservice
    build:
      context: .
      dockerfile: ClosestDriverService/Dockerfile
    container_name: closestdriverservice
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

  driverservice:
    image: driverservice
    build:
      context: .
      dockerfile: DriverService/Dockerfile
    container_name: driverservice
    ports:
      - 5001:8080
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

  invoiceservice:
    image: invoiceservice
    build:
      context: .
      dockerfile: InvoiceService/Dockerfile
    container_name: invoiceservice
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

  log:
    image: log
    build:
      context: .
      dockerfile: Log/Dockerfile
    container_name: log
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

  passengerservice:
    image: passengerservice
    build:
      context: .
      dockerfile: PassengerService/Dockerfile
    container_name: passengerservice
    ports:
      - 5000:8080
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

  visualizerserver:
    image: visualizerserver
    build:
      context: .
      dockerfile: VisualizerServer/Dockerfile
    container_name: visualizerserver
    ports:
      - 5003:8080
    environment:
      - RABBITMQ_USERNAME=$RMQ_User
      - RABBITMQ_PASSWORD=$RMQ_Pass
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      rabbitmqqueuegenerator:
        condition: service_completed_successfully

volumes:
  rabbitmq_data: